#!/bin/bash

if [[ $1 == "snapshot" && $2 == "nonexistant@foo" ]] ; then
	cat testbin/zfssnapfail
	exit 2
fi

if [[ $1 == "snapshot" && $2 == "zones@foo" ]] ; then
	exit 0
fi

if [[ $1 == "list" && $3 == "name,used,avail,refer,mountpoint,type" ]] ; then
	cat testbin/zfslist
	exit 0
fi

if [[ $1 == "list" && $3 == "name,used,refer,creation" ]] ; then
	cat testbin/zfssnaps
	exit 0
fi
